[workspace]
members = ["client", "server", "pingxelflut"]
package.authors = ["kleines Filmr√∂llchen <filmroellchen@serenityos.org>"]
package.version = "0.1.0"
package.rust-version = "1.78"
package.edition = "2021"

resolver = "2"
